name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [1.8, 11]

    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('ui-validator/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ env.cache-name }}
    - name: Cache maven artifacts
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-jdk-${{ matrix.jdk }}-build-${{ env.cache-name }}
          ${{ runner.os }}-jdk-${{ matrix.jdk }}-build
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Test with Maven
      run: mvn -B verify --file pom.xml
